const { chromium } = require('playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const base = process.env.PREVIEW_URL || 'http://localhost:4173'
const out = process.env.QA_OUTPUT || 'artifacts/modal-20261004'
;(async () => {
  fs.mkdirSync(out, { recursive: true })
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox'] })
  const summary = []
  try {
    for (const [name, width, height] of [['narrow', 390, 844], ['wide', 1440, 1000]]) {
      const page = await browser.newPage({ viewport: { width, height }, ignoreHTTPSErrors: base.startsWith('https:') })
      const errors = []
      page.on('pageerror', e => errors.push(e.message))
      // QA never writes production statistics, including legacy collectors.
      await page.route('**/*', route => {
        const request = route.request(), url = new URL(request.url())
        if (url.origin !== new URL(base).origin || url.pathname.startsWith('/api/') || !['GET', 'HEAD'].includes(request.method())) return route.fulfill({ status: 200, contentType: 'application/json', body: '{}' })
        return route.continue()
      })
      const settle = () => page.waitForTimeout(650)
      await page.goto(`${base}/posts/vpn/?v=modal-20261004`, { waitUntil: 'networkidle' })
      await settle()
      const entry = page.locator('.connection-tools').getByRole('button', { name: '筛选与对比套餐' })
      const dialog = page.getByRole('dialog')
      assert.equal(await page.locator('#connection-selector').count(), 0, 'selector must not occupy article')
      const tableY = await page.locator('#airport-comparison').evaluate(e => Math.round(e.getBoundingClientRect().top + scrollY))
      await page.screenshot({ path: `${out}/article-${name}.png` })
      await entry.scrollIntoViewIfNeeded()
      const readingY = await page.evaluate(() => scrollY)
      await entry.focus(); await page.keyboard.press('Enter'); await dialog.waitFor(); await settle()
      assert(await dialog.getByRole('button', { name: '关闭工具' }).evaluate(e => e === document.activeElement))
      const tool = dialog.locator('#connection-selector')
      await tool.locator('select').nth(1).selectOption('10'); await tool.locator('select').nth(2).selectOption('2000')
      await tool.getByText('当前条件下没有资料完整的月付套餐。', { exact: false }).waitFor()
      await tool.getByRole('button', { name: '重置筛选' }).click()
      await tool.getByRole('button', { name: /^加入对比/ }).nth(0).click(); await tool.getByRole('button', { name: /^加入对比/ }).nth(0).click()
      await tool.getByRole('button', { name: /^比较已选/ }).click()
      assert.equal(await tool.locator('.comparison article').count(), 2)
      await tool.getByRole('button', { name: '取消对比并清空选择' }).click()
      // Native dialog keeps keyboard focus within the modal.
      await dialog.getByRole('button', { name: '关闭工具' }).focus(); await page.keyboard.press('Shift+Tab')
      assert(await dialog.evaluate(e => e.contains(document.activeElement)))
      await dialog.locator('.dialog-content').evaluate(e => { e.scrollTop = e.scrollHeight })
      assert(await dialog.locator('.dialog-content').evaluate(e => e.scrollTop > 0))
      await dialog.locator('.dialog-content').evaluate(e => { e.scrollTop = 0 })
      await page.screenshot({ path: `${out}/selector-${name}.png` })
      await page.keyboard.press('Escape'); await settle()
      assert.equal(await dialog.count(), 0)
      assert(Math.abs(await page.evaluate(() => scrollY) - readingY) <= 2, 'reading position restored')
      assert(await entry.evaluate(e => e === document.activeElement), 'opener focus restored')
      await entry.dblclick(); await dialog.waitFor(); await settle()
      await dialog.getByRole('button', { name: '连接排错', exact: true }).click(); await settle()
      await dialog.locator('#help-issue').selectOption('subscription'); await dialog.getByRole('button', { name: '开始排查' }).click(); await settle()
      await dialog.getByRole('button', { name: '取消排查' }).click(); await settle()
      await dialog.getByRole('button', { name: '重新开始' }).click(); await settle()
      await page.screenshot({ path: `${out}/help-${name}.png` })
      await page.goBack(); await settle(); assert.equal(await dialog.count(), 0, 'back closes switched modal')
      await page.goForward(); await settle(); await dialog.waitFor(); assert(await dialog.locator('#help-client').isVisible())
      await dialog.getByRole('button', { name: '关闭工具' }).dblclick(); await settle(); assert.equal(await dialog.count(), 0)
      await entry.click(); await settle(); await page.mouse.click(2, 2); await settle(); assert.equal(await dialog.count(), 0, 'backdrop closes')
      await page.goto(`${base}/posts/vpn/?v=modal-20261004#connection-selector`, { waitUntil: 'networkidle' }); await settle(); await dialog.waitFor()
      await dialog.getByRole('button', { name: '关闭工具' }).click(); await settle(); assert.equal(await dialog.count(), 0, 'direct link can close without leaving article')
      assert(new URL(page.url()).pathname === '/posts/vpn/')
      await page.goto(`${base}/posts/vpn/?v=modal-20261004#airport-comparison`); await settle(); assert.equal(await dialog.count(), 0)
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1))
      assert.deepEqual(errors, [])
      summary.push({ viewport: name, width, height, tableHeadingY: tableY, passed: true, checks: ['article not occupied by tools', 'empty/reset/comparison', 'keyboard focus trap and restore', 'Esc/backdrop/close', 'scroll restore', 'double open/close', 'switch/cancel/restart', 'Back/Forward', 'old deep links', 'ranking anchor', 'no overflow', 'no page errors'] })
      await page.close()
    }
  } finally { await browser.close() }
  fs.writeFileSync(`${out}/browser.json`, JSON.stringify(summary, null, 2)); console.log(JSON.stringify(summary))
})().catch(e => { console.error(e); process.exitCode = 1 })
