const { chromium } = require('playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const base = process.env.PREVIEW_URL || 'http://localhost:4173'
const out = 'artifacts/ux-20261003'
;(async () => {
  fs.mkdirSync(out, { recursive: true })
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/usr/bin/chromium', args: ['--no-sandbox'] })
  const summary = []
  try {
    for (const [name, width, height] of [['narrow', 390, 844], ['wide', 1440, 1000]]) {
      const page = await browser.newPage({ viewport: { width, height } })
      const errors = []; const events = []
      page.on('pageerror', e => errors.push(e.message))
      page.on('request', r => { if (r.url().includes('/api/stats/events')) events.push(r.url()) })
      await page.goto(`${base}/posts/vpn/`, { waitUntil: 'networkidle' })
      const tool = page.locator('#connection-selector')
      await tool.waitFor()
      await page.screenshot({ path: `${out}/after-vpn-${name}.png` })
      await tool.evaluate(el => el.scrollIntoView({ block: 'start' }))
      await page.waitForTimeout(150)
      await page.screenshot({ path: `${out}/after-selector-${name}.png` })
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'page overflow')
      const select = tool.locator('select')
      await select.nth(0).selectOption('ios')
      assert(await tool.getByRole('link', { name: /Shadowrocket/ }).count() === 1)
      await select.nth(1).selectOption('10'); await select.nth(2).selectOption('2000')
      assert(await tool.getByText('当前条件下没有资料完整的月付套餐。', { exact: false }).isVisible())
      await tool.getByRole('button', { name: '重置筛选' }).click()
      assert(await select.nth(0).inputValue() === 'desktop')
      const add = tool.getByRole('button', { name: /^加入对比/ })
      await add.first().focus(); await page.keyboard.press('Enter')
      assert(await tool.locator('button[aria-pressed="true"]').count() === 1)
      await tool.locator('button[aria-pressed="true"]').click()
      assert(await tool.locator('button[aria-pressed="true"]').count() === 0)
      await add.nth(0).click(); await add.nth(0).click()
      const selected = await tool.locator('button[aria-pressed="true"]').count()
      assert.equal(selected, 2)
      await tool.getByRole('button', { name: /^比较已选/ }).dblclick()
      assert.equal(await tool.locator('.comparison article').count(), 2)
      await page.keyboard.press('Escape')
      assert.equal(await tool.locator('.comparison').count(), 0)
      await tool.getByRole('button', { name: /^比较已选/ }).click()
      await tool.getByRole('button', { name: '取消对比并清空选择' }).click()
      assert.equal(await tool.locator('button[aria-pressed="true"]').count(), 0)
      assert(await tool.getByRole('button', { name: /^比较已选/ }).isDisabled())
      await tool.getByRole('button', { name: /^显示全部/ }).click()
      await add.nth(6).click()
      await tool.getByRole('button', { name: '收起至前 6 家' }).click()
      await add.first().click()
      await tool.getByRole('button', { name: /^比较已选/ }).click()
      assert.equal(await tool.locator('.comparison article').count(), 2, 'hidden selected provider lost')
      await tool.getByRole('button', { name: '取消对比并清空选择' }).click()
      await add.first().click(); await select.nth(1).selectOption('60')
      assert.equal(await tool.locator('button[aria-pressed="true"]').count(), 0)
      for (const href of await tool.locator('a').evaluateAll(links => [...new Set(links.map(a => a.getAttribute('href').split('#')[0]))])) {
        const response = await page.request.get(base + href)
        assert(response.ok(), `broken source ${href}`)
      }
      await page.goto(`${base}/connection-help/`)
      await page.goBack(); await tool.waitFor()
      assert.equal(errors.length, 0, errors.join('\n'))
      assert.equal(events.length, 0, 'local preview transmitted event')
      summary.push({ viewport: name, width, height, passed: true, checks: ['no overflow', 'device guides', 'empty/reset', 'keyboard', 'toggle', 'double comparison', 'escape/back/cancel', 'filter clears selection', 'expand/collapse preserves hidden selection', 'source routes', 'history', 'no browser errors', 'no analytics transmission'] })
      await page.close()
    }
  } finally { await browser.close() }
  fs.writeFileSync(`${out}/selector-browser.json`, JSON.stringify(summary, null, 2))
  console.log(JSON.stringify(summary))
})().catch(e => { console.error(e); process.exitCode = 1 })
